### PR TITLE
Fix/gulp deploy with firebase

### LINKED ISSUE #13: JS: Simplify Switching Main Datasource
Rewrite the angular files so that switching between running the app from Firebase and running the App from Local JSON is easier.

### LINKED ISSUE #22: JS/Gulp : make sure all files are injected with Gulp
In app/index.html we have

```
  <!-- I COULDN'T MANAGE TO INJECT THE FOLLOWING FILES WITH GULP DESPITE OVERWRITES -->
  <!-- THESE JS NEED TO BE CALLED IN THE HEADER FOR DOM MANIPULATION   -->
  <script src="../../bower_components/isotope/js/jquery-1.7.1.min.js"></script>
  <script src="../../bower_components/isotope/jquery.isotope.js"></script>
  <link rel="stylesheet" href="../../bower_components/font-awesome/css/font-awesome.css" />
```

I have tried to inject those files even with Overwriting on their bower.json , I couldn't make those work.
It'd be nice to have all files injected dynamically.

### PR DESCRIPTION
**Pull request by chris-alexander**
Sorry that there's so many changes in this PR. I've refactored a few gulp tasks and made it so that the `dist` version always uses Firebase and does not include the debugging message.

Closes #13 
Partially Fixes #22

### CODE REVIEW

**Comment by chris-alexander** [comment]
You can see how it deployed here: http://chris-alexander.github.io/FCCLND/

**Comment by artitudinale1** [comment]
Hi @chris-alexander  did you fix as well css compiling/injecting issue?
I will check it properly tomorrow.
thanks!

File: gulp-tasks/build.js [hunk 1]
```diff
@@ -1,37 +1,55 @@
...
+  return gulp.src('./dev/app/**/*.html')
+    .pipe(useref())
+    /* This is to ensure that we work from Firebase in production */
+    .pipe(gulpif('*.js', replace('var localData = true;', 'var localData = false;')))
+    .pipe(gulpif('*.js', uglify({ mangle: false }))) // Minify JavaScript
+    .pipe(gulpif('*.js', rev()))
+    .pipe(gulpif('*.css', cleanCss())) // Minify CSS
+    .pipe(gulpif('*.css', rev()))
+    .pipe(revReplace())
+    .pipe(gulpif('*.html', htmlmin({
```
Comment (artitudinale1) [inline gulp-tasks/build.js]: Did we decide to minify HTML as well ? do we actually need that?

File: gulpfile.js [hunk 2]
```diff
@@ -1,10 +1,9 @@
...
+ */
 
-// CALLING ALL TASKS WE NEED FOR DEVELOPMENT
-gulp.task('default', [ 'inject', 'script', 'build', 'server'], function () {
+var gulp = require('gulp');
+require('require-dir')('./gulp-tasks'); // Modularised Gulp Tasks
 
-});
+/* Default Task */
+gulp.task('default', ['serve-dev']);
```
Comment (artitudinale1) [inline gulpfile.js:9]: didn't actually test it yet but when start with `gulp` is now running just dev environment? Do we have a way to test locally what is happening in `/dist`?

File: dev/app/app.js [hunk 3]
```diff
@@ -1,6 +1,11 @@
 'use strict';
 
 /**
+ * Change to switch between local JSON and firebase
+ */
+var localData = true;
+
```
Comment (artitudinale1) [inline dev/app/app.js:5]: Are people now able to change this and commit it with other value?

File: gulp-tasks/build.js (hunk 1 above)
Comment (chris-alexander) [inline gulp-tasks/build.js]: We don't necessarily need it but it doesn't hurt either way. I can get rid of it if you want :)

File: gulpfile.js (hunk 2 above)
Comment (chris-alexander) [inline gulpfile.js:9]: Yes if you run `gulp serve-build` it will run that. I just thought it was unnecessary to run both by default. Let me know what you think.

File: dev/app/app.js (hunk 3 above)
Comment (chris-alexander) [inline dev/app/app.js:5]: They can change it and commit but the `dist` version is always firebase no matter what they change this to.

File: gulpfile.js (hunk 2 above)
Comment (artitudinale1) [inline gulpfile.js:9]: So we may need to tell people how to check both `dist` and `dev` - nop?

File: gulp-tasks/build.js [hunk 4]
```diff
@@ -1,37 +1,55 @@
-var gulp = require('gulp'),
-    minCSS = require('gulp-clean-css'),
-    jshint = require('gulp-jshint'),
-    stylish = require('jshint-stylish'),
-    rev = require('gulp-rev'),
-    uglify = require('gulp-uglify'),
-    del = require('del');
-    usemin = require('gulp-usemin')
+var gulp = require('gulp');
+var useref = require('gulp-useref');
```
Comment (artitudinale1) [inline gulp-tasks/build.js:2]: is not better to not write `var` ? is less code.  I will look into rarefaction more : we can maybe use something like `require("gulp-load-plugins")`

File: dev/app/app.js (hunk 3 above)
Comment (artitudinale1) [inline dev/app/app.js:5]: So every time you checkout a branch can be randomly set from local or firebase and you need to check where you are working from? 
Are people able to check all scenarios: `dist` with both local and firebase? and same for `dev`?

File: gulp-tasks/build.js [hunk 5]
```diff
@@ -1,37 +1,55 @@
...
 
-//BUNDLE FILES INTO ONE
-gulp.task('usemin', function () {
-  return gulp.src('dev/app/**/*.html')
-      .pipe(usemin({
-        js: [rev()],
-        css:[minCSS(),rev()]
-              }))
-      .pipe(gulp.dest('dist/app'));
+/**
```
Comment (artitudinale1) [inline gulp-tasks/build.js:27]: this concat process seems a bit long? ...still didn't test it but how long it takes ? didn't work with `usemin`?

File: gulp-tasks/build.js (hunk 4 above)
Comment (chris-alexander) [inline gulp-tasks/build.js:2]: I think there's some debate on which one is better, but we can revisit this later once we pick a styleguide?

I was thinking of using `var $ = require('gulp-load-plugins');` but I thought we could do that later. I didn't want to change too much! I know I already have changed quite a bit haha

File: gulp-tasks/build.js (hunk 5 above)
Comment (chris-alexander) [inline gulp-tasks/build.js:27]: yeah it does take about 3 seconds. I couldn't get `usemin` to work properly and I read somewhere that `useref` is more gulp-friendly. `usemin` was also blacklisted from the google-web-starter (I think that's what it is called). I think I will revisit this whole thing and try using `browserify` which seems to be more up-to-date with what people are using.

File: gulpfile.js (hunk 2 above)
Comment (chris-alexander) [inline gulpfile.js:9]: Yes I will need to update the `README` for this. I think I should just briefly explain each of the gulp tasks.

File: dev/app/app.js (hunk 3 above)
Comment (chris-alexander) [inline dev/app/app.js:5]: When you're working on `dev` then yes it can be changed. I'm not sure how to enforce a rule to always set it back to `true` before committing. Maybe it is something we can do with a test or using travis-ci.

If we want the option of using local files with `dist` then I guess one solution would be to create a separate `build` task for deployment and one for viewing the `dist` version.

Comment (artitudinale1) [inline dev/app/app.js:5]: I think it would be better give all scenarios to test. It's safer and you will be amazed what people can do : break the unbreakable. Personally I prefer have  variable scenario outside `gulp`. Just have a file as before that they can't commit but they can change it to test. I wouldn't have more than two test with gulp: one for `dist` and one for `dev`. I think it would be cleaner.

Change back a variable is no task for a test not sure about travis-ci, but I d rather keep simple and sever. Thay can't commit file the value in repo doesn't change.

File: gulp-tasks/build.js (hunk 4 above)
Comment (artitudinale1) [inline gulp-tasks/build.js:2]: We will need to agree a style before share - would be better - nop?

Changes is good, means you have been worked on it. 
The fun is get all the best solution from everyone contribute and get them work together. 
But yep ! I was thinking to use `var $ = require('gulp-load-plugins');` as well

File: gulp-tasks/build.js (hunk 5 above)
Comment (artitudinale1) [inline gulp-tasks/build.js:27]: You mean https://www.npmjs.com/package/gulp-browserify ?

Comment (chris-alexander) [inline gulp-tasks/build.js:27]: I think it is just browserify plus another one called vinyl something. I'll have to check when I'm home

File: gulpfile.js (hunk 2 above)
Comment (artitudinale1) [inline gulpfile.js]: ok - send me the links. I reckon we need to split task on those .

File: .bowerrc [hunk 6]
```diff
@@ -0,0 +1,6 @@
+{
+  "directory": "bower_components",
+  "scripts": {
+    "postinstall": "gulp inject"
```
Comment (chris-alexander) [inline .bowerrc:4]: This bit means that when you add a new bower dependency it will automatically inject it into index.html :smile:

File: bower.json [hunk 7]
```diff
@@ -22,7 +22,14 @@
...
+    "imagesloaded": "^4.1.0",
+    "isotope": "^1.5.21"
+  },
+  "overrides": {
+    "font-awesome": {
+      "main": [
+        "css/font-awesome.css"
+      ]
+    }
   }
```
Comment (chris-alexander) [inline bower.json:28]: The `"overrides"` section fixes the inject task. It fails because the package itself does not specify what the main file is so inject doesnt know what to import.

Comment (artitudinale1) [inline bower.json:28]: Yep! knew that ...if you saw in the ticket comment I mention I tried that  and didn't work : glad u made it .

Comment (chris-alexander) [inline bower.json:28]: I couldn't get isotope to work properly though :crying_cat_face:

Comment (artitudinale1) [inline bower.json:28]: No, worries I will try to see if I more lucky this time :)

Comment (chris-alexander) [inline bower.json:28]: I think it works if we use the most recent version of isotope but when I tried to update it the view which uses it broke completely, so it would have to be rewritten. Did you know that we are using an old version of isotope?

Comment (artitudinale1) [inline bower.json:28]: You should be able to inject a file despite its version whichever version you specify in bower.json  should be ok to be injected.
I was aware it was an old version ...but I don't remember more why :P...there was a reason .....I will have a look and let u know!...but i wouldn't worry too much we want to drop isotope and Jquery so I dn't be fussy about it.

File: gulp-tasks/build.js (hunk 4 above)
Comment (chris-alexander) [inline gulp-tasks/build.js:2]: I want to do this and change the way it is modularised so it is more readable as in method 2 here: http://macr.ae/article/splitting-gulpfile-multiple-files.html
Can I open a new issue for this and work on it after this PR is merged?

Comment (artitudinale1) [inline gulp-tasks/build.js:2]: Wait this to be merged. There s already stuff to sort out as it is. We need to break it in task and divide between us,

File: gulp-tasks/build.js (hunk 5 above)
Comment (artitudinale1) [inline gulp-tasks/build.js:27]: ok - send me the links. I reckon we need to split task on those .

I reckon is this one http://browserify.org/
I think it s more urgent than the rest. We ll need to divide tasks.

File: dev/app/app.js (hunk 3 above)
Comment (artitudinale1) [inline dev/app/app.js:5]: I would go back regarding this. Keeping variable in separate file and have two task gulp for dev and dist.
